# Generated by Django 3.0.4 on 2020-03-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease_Name', models.CharField(max_length=50)),
                ('Disease_image', models.ImageField(upload_to='pics')),
                ('Disease_Symptoms', models.TextField()),
                ('Disease_Cause', models.CharField(max_length=30)),
                ('Disease_Management', models.TextField(max_length=30)),
                ('Crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrishiGyan.Crops', to_field='name')),
            ],
        ),
    ]
