# Generated by Django 3.0.4 on 2020-03-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0003_auto_20200311_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='Disease_Management',
            field=models.TextField(),
        ),
    ]
