# Generated by Django 3.0.4 on 2020-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0004_auto_20200311_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticides',
            name='Pesticide_Quantity',
            field=models.CharField(default='1L', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesticides',
            name='Pesticide_Price',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
