# Generated by Django 3.0.4 on 2020-03-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0005_auto_20200312_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticides',
            name='Pesticide_Detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
