# Generated by Django 3.0.4 on 2020-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0006_pesticides_pesticide_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticides',
            name='Pesticide_Price',
            field=models.FloatField(),
        ),
    ]
