# Generated by Django 3.0.3 on 2020-03-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0007_auto_20200312_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticides',
            name='Disease',
        ),
        migrations.CreateModel(
            name='PesticideDisease',
            fields=[
                ('ide', models.AutoField(primary_key=True, serialize=False)),
                ('Disease_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrishiGyan.Diseases', to_field='Disease_Name')),
                ('Pesticide_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrishiGyan.Pesticides', to_field='Pesticide_Name')),
            ],
        ),
    ]
