# Generated by Django 3.0.3 on 2020-03-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0008_auto_20200321_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('Down_vote', models.IntegerField(default=0)),
                ('Up_vote', models.IntegerField(default=0)),
                ('Email', models.CharField(max_length=50)),
                ('ide', models.AutoField(primary_key=True, serialize=False)),
                ('Disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrishiGyan.Diseases', to_field='Disease_Name')),
                ('Pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrishiGyan.Pesticides', to_field='Pesticide_Name')),
            ],
        ),
    ]
