# Generated by Django 3.0.3 on 2020-03-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0010_auto_20200323_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Disease',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='Pesticide',
            field=models.CharField(max_length=50),
        ),
    ]
