# Generated by Django 3.0.3 on 2020-03-25 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0011_auto_20200323_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CropName', models.CharField(max_length=50)),
                ('Questions', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('Email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
