# Generated by Django 3.0.3 on 2020-03-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0013_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='Qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrishiGyan.Question'),
        ),
    ]
