# Generated by Django 3.0.3 on 2020-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiGyan', '0015_auto_20200328_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='pics'),
            preserve_default=False,
        ),
    ]
